name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_android:
    name: Build android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: |
          composeApp/build/outputs/apk/debug/composeApp-debug.apk
          composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk

  build_desktop:
    name: Build desktop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageUberJarForCurrentOS

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop
        path: |
          composeApp/build/compose/jars/

  build_web:
    name: Build web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew wasmJsBrowserDistribution

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: |
          composeApp/build/dist/wasmJs/productionExecutable
